services:
  - type: web
    name: videointerviewer
    runtime: node
    rootDir: .
    buildCommand: cd Frontend && npm install && npm run build && cd ../Backend && npm install && npm run build
    startCommand: cd Backend && npm start
    envVars:
      - key: PRODUCTION
        value: TRUE
      - key: PORT
        value: 3001
      - key: INNGEST_DEV
        value: 0
      - key: DB_URL
        sync: false
      - key: INNGEST_EVENT_KEY
        sync: false
      - key: INNGEST_SIGNING_KEY
        sync: false
      - key: STREAM_API_KEY
        sync: false
      - key: STREAM_API_SECRET
        sync: false
      - key: CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLERK_SECRET_KEY
        sync: false
      - key: VITE_CLERK_PUBLISHABLE_KEY
        sync: false
      - key: CLIENT_URL
        sync: false
